#common
spring:
  profiles:
    active: local
  config:
    import: application-core.yml

jwt:
  secretKey: MDswDQYJKoZIhvcNAQEBBQADKgAwJwIgX7W5hUvtc8sbNAPy286U1noeLcgUZP3ItFU0oU9WkKECAwEAAQ==

servlet:
   multipart:
    max-file-size: 10MB

--- # local
spring:
  config:
    activate:
      on-profile: local


--- # dev
spring:
  config:
    activate:
      on-profile: dev

--- # prod
spring:
  config:
    activate:
      on-profile: prod