#common
spring:
  profiles:
    include: common

  jpa:
   database-platform: org.hibernate.dialect.H2Dialect
   hibernate:
     ddl-auto: update
     use-new-id-generator-mappings: false
     open-in-view: false
     show-sql: true
     properties:
       hibernate:
         format_sql: true
         type: trace
         default_batch_fetch_size: 1000


--- #local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpa
    username: sa
    password:

--- #dev
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpa
    username: sa
    password:

--- #prod
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpa
    username: sa
    password:


